echo "Begin deploy demo"
echo "Begin deploy demo"
echo "$CI_PULL_REQUEST"
echo "Begin deploy demo"
echo "Begin deploy demo"
echo "$CI_PULL_REQUESTS"
echo "Begin deploy demo"
echo "Begin deploy demo"
echo "$CIRCLE_TAG"
echo "Begin deploy demo"

