echo "Begin deploy master"
echo "Begin deploy master"
echo "Begin deploy master"
echo "$CI_PULL_REQUEST"
echo "Begin deploy master"
echo "Begin deploy master"
echo "$CI_PULL_REQUESTS"
echo "Begin deploy master"
echo "$CIRCLE_USERNAME"
echo "Begin deploy master"