echo "Begin deploy release"
echo "Begin deploy release"
echo "$CI_PULL_REQUEST"
echo "Begin deploy release"
echo "Begin deploy release"
echo "$CI_PULL_REQUESTS"
echo "Begin deploy release"
echo "Begin deploy release"
echo "$CIRCLE_TAG"
echo "Begin deploy release"

