echo "Begin deploy prerelease"
echo "Begin deploy prerelease"
echo "$CI_PULL_REQUEST"
echo "Begin deploy prerelease"
echo "Begin deploy prerelease"
echo "$CI_PULL_REQUESTS"
echo "Begin deploy prerelease"
echo "Begin deploy prerelease"
echo "$CIRCLE_TAG"
echo "Begin deploy feature"

